name: FoD scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: fortify-actions/setup-scancentral-client@v1
      - uses: fortify-actions/setup-fod-uploader@v1
      - run: scancentral package -bt gradle -o BugTrackerPluginALMOctane.zip
      - run: java -jar $FOD_UPLOAD_JAR -bsi "$FOD_BSI" -z BugTrackerPluginALMOctane.zip -uc "$FOD_USER" "$FOD_PWD" -ep 2 -pp 1
        env:
          FOD_BSI: ${{ secrets.FOD_BSI }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PWD: ${{ secrets.FOD_PWD }}
